export const ADMIN_PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PURCHASE_REQUESTS_VIEW: 'PURCHASE_REQUESTS_VIEW',
  PURCHASE_REQUESTS_EDIT: 'PURCHASE_REQUESTS_EDIT',
  ORDERS_VIEW: 'ORDERS_VIEW',
  ORDERS_EDIT: 'ORDERS_EDIT',
  ORDERS_DELETE: 'ORDERS_DELETE',
  PRODUCTS_VIEW: 'PRODUCTS_VIEW',
  PRODUCTS_CREATE: 'PRODUCTS_CREATE',
  PRODUCTS_EDIT: 'PRODUCTS_EDIT',
  PRODUCTS_DELETE: 'PRODUCTS_DELETE',
  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW',
  WAREHOUSE_EDIT: 'WAREHOUSE_EDIT',
  LAPTOPS_VIEW: 'LAPTOPS_VIEW',
  LAPTOPS_EDIT: 'LAPTOPS_EDIT',
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_EDIT: 'CUSTOMERS_EDIT',
  PAYMENTS_VIEW: 'PAYMENTS_VIEW',
  PAYMENTS_EDIT: 'PAYMENTS_EDIT',
  SHIPMENTS_VIEW: 'SHIPMENTS_VIEW',
  SHIPMENTS_EDIT: 'SHIPMENTS_EDIT',
  FINANCIAL_REPORTS_VIEW: 'FINANCIAL_REPORTS_VIEW',
  BRANDS_MANAGE: 'BRANDS_MANAGE',
  STORES_MANAGE: 'STORES_MANAGE',
  CATEGORIES_MANAGE: 'CATEGORIES_MANAGE',
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_EDIT: 'SETTINGS_EDIT',
  ADMIN_USERS_MANAGE: 'ADMIN_USERS_MANAGE',
  ACTIVITY_LOGS_VIEW: 'ACTIVITY_LOGS_VIEW',
});

const P = ADMIN_PERMISSIONS;
const ALL_PERMISSIONS = Object.freeze(Object.values(P));

export const ADMIN_ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: ALL_PERMISSIONS,
  ADMIN: ALL_PERMISSIONS.filter(permission => permission !== P.ADMIN_USERS_MANAGE),
  OPERATIONS: Object.freeze([
    P.DASHBOARD_VIEW,
    P.PURCHASE_REQUESTS_VIEW,
    P.PURCHASE_REQUESTS_EDIT,
    P.ORDERS_VIEW,
    P.ORDERS_EDIT,
    P.WAREHOUSE_VIEW,
    P.WAREHOUSE_EDIT,
    P.SHIPMENTS_VIEW,
    P.SHIPMENTS_EDIT,
  ]),
  FINANCE: Object.freeze([
    P.DASHBOARD_VIEW,
    P.PAYMENTS_VIEW,
    P.PAYMENTS_EDIT,
    P.FINANCIAL_REPORTS_VIEW,
  ]),
  CONTENT: Object.freeze([
    P.DASHBOARD_VIEW,
    P.PRODUCTS_VIEW,
    P.PRODUCTS_CREATE,
    P.PRODUCTS_EDIT,
    P.PRODUCTS_DELETE,
    P.BRANDS_MANAGE,
    P.STORES_MANAGE,
    P.CATEGORIES_MANAGE,
  ]),
});

export function getPermissionsForRole(role) {
  return ADMIN_ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(admin, permission) {
  if (!admin || !permission) return false;
  const permissions = Array.isArray(admin.permissions)
    ? admin.permissions
    : getPermissionsForRole(admin.role);
  return permissions.includes(permission);
}
