// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    // Migrations should bypass the Neon pooler when DIRECT_URL is configured.
    // Runtime traffic continues to use pooled DATABASE_URL in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
