import {
  AirplaneTilt,
  Bag,
  Bell,
  Briefcase,
  Check,
  CheckCircle,
  Circle,
  ClipboardText,
  CoatHanger,
  CreditCard,
  DeviceMobile,
  EnvelopeSimple,
  FileText,
  Fire,
  FirstAidKit,
  FolderOpen,
  GameController,
  Gear,
  Globe,
  Handbag,
  Headphones,
  Heart,
  Hourglass,
  InstagramLogo,
  Key,
  Laptop,
  Lightning,
  LinkSimple,
  Lock,
  MagnifyingGlass,
  MapPin,
  Package,
  PaperPlaneTilt,
  PencilSimple,
  Phone,
  Plus,
  Question,
  RocketLaunch,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smiley,
  SneakerMove,
  Star,
  Tag,
  TelegramLogo,
  Trash,
  TShirt,
  Watch,
  WhatsappLogo,
  X,
  XCircle,
} from '@phosphor-icons/react';

const icons = {
  airplane: AirplaneTilt,
  bag: Bag,
  bell: Bell,
  briefcase: Briefcase,
  check: Check,
  checkCircle: CheckCircle,
  circle: Circle,
  clipboard: ClipboardText,
  clothing: TShirt,
  coat: CoatHanger,
  creditCard: CreditCard,
  electronics: Headphones,
  envelope: EnvelopeSimple,
  file: FileText,
  fire: Fire,
  firstAid: FirstAidKit,
  folder: FolderOpen,
  game: GameController,
  gear: Gear,
  globe: Globe,
  handbag: Handbag,
  heart: Heart,
  hourglass: Hourglass,
  instagram: InstagramLogo,
  key: Key,
  laptop: Laptop,
  lightning: Lightning,
  link: LinkSimple,
  lock: Lock,
  mobile: DeviceMobile,
  package: Package,
  pencil: PencilSimple,
  phone: Phone,
  pin: MapPin,
  plus: Plus,
  question: Question,
  rocket: RocketLaunch,
  search: MagnifyingGlass,
  shield: ShieldCheck,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  smile: Smiley,
  sneaker: SneakerMove,
  star: Star,
  tag: Tag,
  telegram: TelegramLogo,
  trash: Trash,
  watch: Watch,
  whatsapp: WhatsappLogo,
  x: X,
  xCircle: XCircle,
  paperPlane: PaperPlaneTilt,
};

export default function MinimalIcon({ name, size = 20, weight = 'regular', className, style, ...props }) {
  const Icon = icons[name];
  if (!Icon) return null;

  return (
    <Icon
      aria-hidden="true"
      className={className}
      size={size}
      weight={weight}
      style={{ flexShrink: 0, verticalAlign: 'middle', ...style }}
      {...props}
    />
  );
}
